export const NEW_MESSAGE = "NEW_MESSAGE";
export const USER_DATA = "USER_DATA";
export const SEARCH_RESULT = "SEARCH_RESULT";
export const DEACTIVATE_SEARCH_RESULT = "DEACTIVATE_SEARCH_RESULT";
export const ADD_FRIEND = "ADD_FRIEND";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const TEMP_CHAT_ID = "TEMP_CHAT_ID";
export const SET_FRIEND = "SET_FRIEND";
